services:
  diplomacy:
    build: ai_animation
    ports:
      - "4173:4173"
      - "5173:5173"
  diplomacy-dev:
    build: ai_animation
    ports:
      - "4173:4173"
      - "5173:5173"
    command: ["npm", "run", "dev-all"]
    volumes:
      - "./ai_animation/:/app/"
